name: Trigger Jenkins Job

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Trigger Jenkins Build
      uses: appleboy/jenkins-action@v1
      with:
        url: ${{ secrets.JENKINS_URL }}
        user: ${{ secrets.JENKINS_USER }}
        token: ${{ secrets.JENKINS_API_TOKEN }}
        job: API
        # Optional: set wait to true to wait for job completion
        wait: true 